### PR TITLE
Fixed mysql error on install

### PR DESCRIPTION
**Pull request by carcam**

### CODE REVIEW

**Comment by GeraintEdwards** [comment]
Actually the problem was not quite what you say in your commit message.  The correct code should be 
```php
		if (!array_key_exists("evaccess", $icols))
		{
                    // What is curtent value of sql_mode
                    $db->setQuery("SELECT @@sql_mode");
                    $sql_mode = @$db->loadResult();
                    
                    $db->setQuery("SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE',''))");
                    @$db->execute();
                    $sql = "ALTER TABLE #__jevents_vevent ADD INDEX evaccess (access)";
                    $db->setQuery($sql);
                    @$db->execute();
                    
                    // Return to old value
                    $db->setQuery("SET SESSION sql_mode=(".$db->quote($sql_mode).")");
                    @$db->execute();                    
		}
```

**Comment by GeraintEdwards** [comment]
We need to know the old value and return it to what it was before.

**Comment by GeraintEdwards** [comment]
I am pushing this modified version so will close this PR.

I'm guessing it probably only had an impact when debug mode was enabled ??  The reason it worked on the second pass was that the index had been created before the error message arose.  Good work tracking down the location of the problem

**Comment by carcam** [comment]
Hi @GeraintEdwards we do not need to know the previous value as we just concatenate the NO_ZERO_DATE mode and then me remove only that specific mode with no changes to previously settled modes ;)

**Pull request closed without merging**
