### PR TITLE
Modal quick hide/close for event manage dialog fix

### PR DESCRIPTION
**Pull request by tonypartridge**
Drops native bootstrap data modals and uses our JS to work when conflicts occur. 

Adds ID based modal window.

### CODE REVIEW

**Comment by GeraintEdwards** [comment]
Where is this causing a problem?

**Comment by tonypartridge** [comment]
@geraintedwarda where isn’t it? When bootstrap 2/3 loads it’s a problem when the modal quickly hides we have had it for years. There’s about 3 forums posts last week because of this, tested and his fixes the solution on their site and works perfectly fine for my test cases.

**Comment by GeraintEdwards** [comment]
The issue was that people were loading bootstrap twice on the same page.

Does change resolve that problem?

**Comment by tonypartridge** [comment]
Yep this one does! Tested and working 👊

**Comment by ctshelp** [comment]
I have tried to add this fix but i must be in the wrong place. Can you please step me through which files i have to modify. I cant seem to find the exact directories you are referring to. Thank you

**Comment by tonypartridge** [comment]
@ctshelp So the live locations would be:

/components/com_jevents/assets/css/eventsadmin.css
/components/com_jevents/assets/js/editpopupJQ.js
/components/com_jevents/views/default/helpers/defaulteventmanagementbutton.php

**Comment by ctshelp** [comment]
Thank you very much. I will see if I can find them.

**Comment by ctshelp** [comment]
Please excuse me I am very green in Joomla and PHP. Do I do this work in the JEvents - Core: Custom CSS?
Or Is it in the Directories with in the Template?
Thank you again for your help

**Comment by tonypartridge** [comment]
Hello, no you edit the files directly as per the file changes github lists, remove the red highlighted code and replace it with the green. You could also download the whole file in the change and replace you file.

**Comment by ctshelp** [comment]
I am having a heck of a time finding the live files.



*From:* Tony Partridge [mailto:notifications@github.com]
*Sent:* Tuesday, March 20, 2018 9:25 AM
*To:* JEvents/JEvents <JEvents@noreply.github.com>
*Cc:* ctshelp <michael@rgwcd.org>; Mention <mention@noreply.github.com>
*Subject:* Re: [JEvents/JEvents] Modal quick hide/close for event manage
dialog fix (#423)



Hello, no you edit the files directly as per the file changes github lists,
remove the red highlighted code and replace it with the green. You could
also download the whole file in the change and replace you file.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JEvents/JEvents/pull/423#issuecomment-374639224>, or mute
the thread

**Comment by ctshelp** [comment]
Tony,

I am in the right directory after all. I am just struggling to find the
exact files. Thank you again

Michael

**Pull request merged**
