### PR TITLE
Added the namespace path for toolbar and removed the include. 

### PR DESCRIPTION
**Pull request by skurvish**
The included file libraries/src/toolbar.php was removed in J3.9

### CODE REVIEW

**Comment by tonypartridge** [comment]
This wouldn’t work as it calls in Toolbar not JToolbar and JToolbar is already included by the parent view. 

What error have you seen to include this? 

Note we have removed the toolbar call in the latest jQuery branch which I will merge into jQuery-35 branch on Monday.

**Comment by skurvish** [comment]
The error was reported in 2 posts on the JEvents support forum. The include for the libraries/src/toolbar.php fails as this file was removed in J3.9. Perhaps we simply need to drop the include?

**Comment by tonypartridge** [comment]
Ahh it’s already been resolve in the JQuery branch 😜.

Sorry the master is out dated as myself and Geraint develops against jUqeey and release from that and merge that into master post release.

**Comment by tonypartridge** [comment]
Note it was also called from /administrator/includes/toolbar.php which was removed. Joomla! Decided it was never used 😂

**Pull request closed without merging**
